; Place equivalent keys in host64\ReShade.ini.

[GENERAL]
EffectSearchPaths=.\reshade-shaders\Shaders\**
TextureSearchPaths=.\reshade-shaders\Textures\**

[INPUT]
KeyOverlay=36,0,0,0

[RenoDX.DLSS5]
EnableHooks=2
NeuralUplift=1
NREnableUpscaling=0
NRPreset=0
NRStyle=0
NRIntensity=1
NRLocalTone=1
NRLocalStructure=1
NRAutoMask=1
NRUICorrection=1
